### ISSUE TITLE
Unable To Use Dynamic Configuration in DNSClass

### ISSUE THREAD

**Issue by mlladb** [eminaktas/kubedns-shepherd#31]
I'm having issues using Dynamic Configuration in DNSClass. I've been trying the configurations based on [samples.](https://github.com/eminaktas/kubedns-shepherd/tree/main/config/samples).
With any configuration I try to use I get the following error.

```
apiVersion: config.kubedns-shepherd.io/v1alpha1
kind: DNSClass
metadata:
  name: kubedns-shepherd-dnsclass
spec:
  allowedDNSPolicies:
  - ClusterFirst
  - ClusterFirstWithHostNet
  - None
  allowedNamespaces:
  - kubedns-shepherd
  disabledNamespaces:
  - kube-system
  dnsConfig:
    nameservers:
    - 172.20.0.10
    options:
    - name: ndots
      value: "3"
    - name: edns0
    searches:
    - svc.cluster.local
    - cluster.local
    - '{{ .podNamespace }}.svc.cluster.local'
  dnsPolicy: None
status:
  conditions:
  - lastTransitionTime: "2024-10-14T04:29:52Z"
    message: Ready
    reason: ReconcileCompleted
    status: "True"
    type: ready
  - lastTransitionTime: "2024-10-14T04:35:28Z"
    message: 'failed to discover template keys: nameservers, clusterDomain, clusterName,
      dnsDomain'
    reason: ReconcileError
    status: "True"
    type: error
  discoveredFields: {}
  state: error
```

The cluster domain key is configured in my kublet config as, `"clusterDomain": "cluster.local"`, I don't mind hard coding this as it should be the same across all clusters and environments but I would like to make use of `podNamespace`.

I have tried the following configs.

clusterDomain and podNamespace.
```yaml
 searches:
    - svc.{{ .clusterDomain }}
    - '{{ .podNamespace }}.svc.{{ .clusterDomain }}'
```

podNamespace
```yaml
searches:
    - svc.cluster.local
    - '{{ .podNamespace }}.svc.cluster.local'
```

Kubernetes version
```
Server Version: v1.29.8-eks-a737599
```

Can you offer any advice on how to get this working?
